name: Deploy API

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21'

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull rafaelsantos15/express-notify:latest

      - name: Remove old docker container
        run: docker rm -f express-notify

      - name: Run docker container
        run: docker run -d -p 3002:3002 -e USERNAME_EMAIL='${{secrets.USERNAME_EMAIL}}' -e SEND_EMAIL_TOPIC_ERROR=${{secrets.SEND_EMAIL_TOPIC_ERROR}} -e APP_KEY_ICARO=${{secrets.APP_KEY_ICARO}} -e PORT_EMAIL=${{secrets.PORT_EMAIL}} -e PASSWORD_EMAIL=${{secrets.PASSWORD_EMAIL}} -e HOST_EMAIL=${{secrets.HOST_EMAIL}} -e EMAIL_SERVICE=${{secrets.EMAIL_SERVICE}} -e BROKERS_KAFKA=${{secrets.BROKERS_KAFKA}} --name express-notify rafaelsantos15/express-notify
